# Generated by Django 5.2.7 on 2025-12-07 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id_conta', models.BigAutoField(primary_key=True, serialize=False)),
                ('numero_conta', models.CharField(max_length=20, unique=True)),
                ('tipo_conta', models.CharField(choices=[('corrente', 'Corrente'), ('poupanca', 'Poupança')], max_length=20)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status_conta', models.CharField(choices=[('ativa', 'Ativa'), ('bloqueada', 'Bloqueada')], default='ativa', max_length=20)),
                ('data_abertura', models.DateField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Extrato',
            fields=[
                ('id_extrato', models.BigAutoField(primary_key=True, serialize=False)),
                ('data_emissao', models.DateField(auto_now_add=True)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.conta')),
            ],
        ),
    ]
