# Generated by Django 5.2.7 on 2025-12-07 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.BigAutoField(primary_key=True, serialize=False)),
                ('isAdm', models.BooleanField(default=False)),
                ('nome', models.CharField(max_length=150)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(max_length=20)),
                ('senha', models.CharField(max_length=255)),
                ('data_cadastro', models.DateField(auto_now_add=True)),
                ('gerente_responsavel', models.ForeignKey(blank=True, limit_choices_to={'isAdm': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_gerenciados', to='usuarios.usuario')),
            ],
        ),
    ]
