# Generated by Django 5.2.7 on 2025-12-07 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoCredito',
            fields=[
                ('id_solicitacaoCredito', models.BigAutoField(primary_key=True, serialize=False)),
                ('valor_solicitado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('taxa_juros', models.FloatField()),
                ('status_credito', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='pendente', max_length=20)),
                ('data_solicitacao', models.DateField(auto_now_add=True)),
                ('data_analise', models.DateField(blank=True, null=True)),
                ('gerente_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analises_credito', to='usuarios.usuario')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
        ),
    ]
