# Generated by Django 6.0 on 2025-12-08 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('concluida', 'Concluída'), ('falhou', 'Falhou')], default='concluida', max_length=20),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='descricao',
            field=models.TextField(blank=True, default='Transferência realizada', null=True),
        ),
    ]
