# Generated by Django 5.2.7 on 2025-12-07 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contas', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartao',
            fields=[
                ('id_cartao', models.BigAutoField(primary_key=True, serialize=False)),
                ('numero_cartao', models.CharField(max_length=20, unique=True)),
                ('limite_atual', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status_cartao', models.CharField(choices=[('solicitado', 'Solicitado'), ('aprovado', 'Aprovado'), ('bloqueado', 'Bloqueado')], max_length=20)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.conta')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitacaoCartao',
            fields=[
                ('id_solicitacaoCartao', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo_cartao', models.CharField(choices=[('credito', 'Crédito'), ('debito', 'Débito')], max_length=20)),
                ('status_solicitacao', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='pendente', max_length=20)),
                ('data_solicitacao', models.DateField(auto_now_add=True)),
                ('data_analise', models.DateField(blank=True, null=True)),
                ('gerente_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analises_cartao', to='usuarios.usuario')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_cartao', to='usuarios.usuario')),
            ],
        ),
    ]
