# Generated by Django 5.2.7 on 2025-12-11 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCartao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('categoria', models.CharField(choices=[('debito', 'Débito'), ('credito', 'Crédito')], max_length=20)),
                ('cor', models.CharField(max_length=20)),
                ('limite_minimo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('limite_maximo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('beneficios', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='cartao',
            name='tipo_cartao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cartoes.tipocartao'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solicitacaocartao',
            name='tipo_cartao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cartoes.tipocartao'),
        ),
    ]
