# Generated by Django 5.2.7 on 2025-12-11 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartoes', '0002_tipocartao_cartao_tipo_cartao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipocartao',
            name='cor',
            field=models.CharField(choices=[('cartao-debito', 'Débito Azul'), ('cartao-gold', 'Gold'), ('cartao-platinum', 'Platinum'), ('cartao-black', 'Black')], default='cartao-debito', max_length=20),
        ),
    ]
