# Generated by Django 5.2.7 on 2025-12-12 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartoes', '0003_alter_tipocartao_cor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipocartao',
            name='cor',
        ),
        migrations.AddField(
            model_name='tipocartao',
            name='codigo',
            field=models.CharField(choices=[('debito', 'Débito (Débito)'), ('gold', 'Gold (Crédito)'), ('platinum', 'Platinum (Crédito)'), ('black', 'Black (Crédito)')], default='debito', max_length=20, unique=True),
        ),
    ]
