# Generated by Django 5.2.7 on 2025-12-12 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartoes', '0004_remove_tipocartao_cor_tipocartao_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartao',
            name='tipo_cartao',
        ),
        migrations.RemoveField(
            model_name='solicitacaocartao',
            name='tipo_cartao',
        ),
        migrations.DeleteModel(
            name='TipoCartao',
        ),
    ]
