# Generated by Django 5.2.7 on 2025-12-15 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartoes', '0005_remove_cartao_tipo_cartao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitacaocartao',
            name='gerente_responsavel',
        ),
        migrations.RemoveField(
            model_name='solicitacaocartao',
            name='solicitante',
        ),
        migrations.DeleteModel(
            name='Cartao',
        ),
        migrations.DeleteModel(
            name='SolicitacaoCartao',
        ),
    ]
