# Generated by Django 5.2.7 on 2025-12-15 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cartoes', '0006_remove_solicitacaocartao_gerente_responsavel_and_more'),
        ('contas', '0002_extrato_descricao_extrato_valor_and_more'),
        ('usuarios', '0002_alter_usuario_cpf'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCartao',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('debito', 'Débito'), ('credito', 'Crédito')], max_length=20)),
                ('limite_minimo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('limite_maximo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('vantagens', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SolicitacaoCartao',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='pendente', max_length=20)),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('data_analise', models.DateTimeField(blank=True, null=True)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.conta')),
                ('gerente_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analises_cartao', to='usuarios.usuario')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
                ('cartao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cartoes.tipocartao')),
            ],
        ),
    ]
