# Generated by Django 5.2.7 on 2025-12-15 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartoes', '0007_initial'),
        ('usuarios', '0002_alter_usuario_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaocartao',
            name='gerente_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cartoes_para_aprovar', to='usuarios.usuario'),
        ),
        migrations.AlterField(
            model_name='solicitacaocartao',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='solicitacaocartao',
            name='solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_cartao', to='usuarios.usuario'),
        ),
        migrations.CreateModel(
            name='CartaoCliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=16, unique=True)),
                ('cvv', models.CharField(max_length=3)),
                ('validade', models.DateField()),
                ('limite', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ativo', models.BooleanField(default=True)),
                ('solicitacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cartoes.solicitacaocartao')),
            ],
        ),
    ]
