# Generated by Django 5.2.7 on 2025-12-15 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartoes', '0008_alter_solicitacaocartao_gerente_responsavel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartaocliente',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='solicitacaocartao',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
