# Generated by Django 5.2.7 on 2025-12-15 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartoes', '0009_alter_cartaocliente_id_alter_solicitacaocartao_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartaocliente',
            name='senha',
            field=models.CharField(default=4857, max_length=4),
            preserve_default=False,
        ),
    ]
